starwars/config/routes.rb
Rails.application.routes.draw do
  root 'people#index'
  get 'people/index', to: 'people#index', as: "people_index"
  get 'people/show:id', to: 'people#show', as: "people_show"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

starwars/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

starwars/app/models/film.rb
class Film < ApplicationRecord
    has_and_belongs_to_many :people
    has_and_belongs_to_many :species
    has_and_belongs_to_many :planets
    has_and_belongs_to_many :vehicles
end

starwars/app/models/person.rb
class Person < ApplicationRecord
    belongs_to :planet
    has_and_belongs_to_many :films
    has_and_belongs_to_many :species
    has_and_belongs_to_many :vehicles

    def specie_name
        if !self.species.first.nil?
            return "Sou um " + self.species.first.name
        else
            return "Eu não conheço minha especie"
        end
    end

    def planet_name
        if !self.planet.nil?
            return "eu nasci em " + self.planet.name
        else
            return "não sei onde nasci"
        end
    end
    def vehicle_name
        if !self.vehicles.empty?
            return "Eu já pilotei " + self.vehicles.map{|v| v.name}.join(" ,")
        else
            return "Eu nunca pilotei"
        end
    end
end

starwars/app/models/planet.rb
class Planet < ApplicationRecord
    has_many :people
end

starwars/app/models/specie.rb
class Specie < ApplicationRecord
end

starwars/app/models/vehicle.rb
class Vehicle < ApplicationRecord
end

starwars/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

starwars/app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: :show  
  def index
    @people = Person.all.page(params[:page]).per(10)
  end
  def show
    
  end

  private
    def set_person
      @person = Person.find(params[:id])
    end
end

starwars/app/helpers/application_helper.rb
module ApplicationHelper
end

starwars/app/helpers/people_helper.rb
module PeopleHelper
end

starwars/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Starwars</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <nav class="navbar fixed-top navbar-dark bg-dark">
        <a class="navbar-brand" href="#">StarWars' introduction</a>
      </nav>
      <br>
      <br>
      <br>
      <div class="row">
        <div class="col-12">
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

starwars/app/views/people/index.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">Id</th>
      <th scope="col">Name</th>
      <th scope="col">Height</th>
      <th scope="col">Mass(kg)</th>
    </tr>
  </thead>
  <tbody>
    <% @people.each do |person| %>
        <tr>
            <th scope="row"><%= link_to person.id, people_show_path(person.id) %></th>
            <td><%= person.name %></td>
            <td><%= person.height %></td>
            <td><%= person.mass %></td>
        </tr>
    <% end %>
    </tbody>
</table>
<%= paginate @people %>

starwars/app/views/people/show.html.erb
<div class="card">
  <div class="card-header">
    Frase de introdução do <%= @person.name %>
  </div>
  <div class="card-body">
    <h5 class="card-title"></h5>
    <p class="card-text">
        Olá, meu nome é <%= @person.name %>. <%= @person.specie_name %> e
        peso <%= @person.mass %> kg, <%= @person.planet_name %> no ano de <%= @person.birth_year %>. <%= @person.vehicle_name %> 
    </p>
    <%= link_to "voltar", people_index_path, :class=>"btn btn-primary" %>
  </div>
</div>